### ISSUE TITLE
Failed to resolve: com.fingerprint.android:pro:2.3.1

### ISSUE THREAD

**Issue by vikashprajapati** [fingerprintjs/fingerprintjs-pro-android-demo#40]
After downloading the project and syncing it, getting this error Failed to resolve: com.fingerprint.android:pro:2.3.1

**Comment by Sergey-Makarov** [comment]
Hey!
I tried to do the same and everything works fine on my end. Could you try to sync the project once again? Maybe it was our reposilite repository being down for a short period of time 🤔

**Comment by vikashprajapati** [comment]
This is what I m getting after sync
`
Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.fingerprint.android:pro:2.3.1.
     Required by:
         project :app
      > Could not resolve com.fingerprint.android:pro:2.3.1.
         > Could not get resource 'https://maven.fpregistry.io/releases/com/fingerprint/android/pro/2.3.1/pro-2.3.1.pom'.
            > Could not GET 'https://maven.fpregistry.io/releases/com/fingerprint/android/pro/2.3.1/pro-2.3.1.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.5/userguide/build_environment.html#gradle_system_properties
                  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`

**Comment by Sergey-Makarov** [comment]
Thanks for these details.

So apparently it looks like your local JDK does not trust the certificate of the repository.
At the moment I am not sure whether it's a popular issue that should be fixed by ourselves or it should simply be fixed on your end.

I've run this url "https://maven.fpregistry.io/releases/com/fingerprint/android/pro/2.3.1/pro-2.3.1.pom" through [ssl checker](https://www.sslshopper.com/ssl-checker.html#hostname=https://maven.fpregistry.io/releases/com/fingerprint/android/pro/2.3.1/pro-2.3.1.pom) and have not found any issues, neither I do experience any problems on my own machine.

I'd suggest you to
1. Try access https://maven.fpregistry.io/releases/com/fingerprint/android/pro/2.3.1/pro-2.3.1.pom from you browser to check whether the issue is not caused by firewalls / internet provider.
2. If the step 1 succeeds, I'd consider adding the certificate of the repository to the list of root CA's of your local JDK used by gradle.

**Comment by Sergey-Makarov** [comment]
@Yogesh-1206 Hey! Could you please go through the steps I listed [above](https://github.com/fingerprintjs/fingerprintjs-pro-android-demo/issues/40#issuecomment-1564011750) and report about the results?

Also, it would be nice to know what OS and Android Studio version you are using.

**Comment by vikashprajapati** [comment]
I tried accessing this url https://maven.fpregistry.io/releases/com/fingerprint/android/pro/2.3.1/pro-2.3.1.pom from browser, Its loading fine. In Android studio while syncing issue is coming

**Comment by Sergey-Makarov** [comment]
Thanks @vikashprajapati 

Will take a look into that, stay tuned 🙂

**Comment by Sergey-Makarov** [comment]
Well, my assumption is that the `cacerts` file of your local JDK runtime does not contain all the necessary certificates, whilst in my case it does.

I am not sure how exactly this file is generated, i.e. what defines the list of CAs in this file and why they are different on our machines.

Anyway, just in order to verify that this is an exact issue, I can offer you to do the following:
1. Get the path to the JDK used by gradle
    1. In Android Studio, go to File -> Project Structure.. -> SDK Location -> Gradle Settings -> Gradle JDK: -> Click on the dropdown list to see the actual path of the JDK. In my case it's /Applications/Android Studio.app/Contents/jbr/Contents/Home . I'll assume you have the same during the following steps.
2. Check whether this JDK trusts amazon root certificates
    1. In terminal, execude the following line (adjust the path based on step 1):
      `/Applications/Android\ Studio.app/Contents/jbr/Contents/Home/bin/keytool -list -cacerts | grep amazon -C 2`
    2. In my case, I have:
      ```
      ...
      amazonrootca1 [jdk], May 26, 2015, trustedCertEntry, 
      Certificate fingerprint (SHA-256): 8E:CD:E6:88:4F:3D:87:B1:12:5B:A3:1A:C3:FC:B1:3D:70:16:DE:7F:57:CC:90:4F:E1:CB:97:C6:AE:98:19:6E
      amazonrootca2 [jdk], May 26, 2015, trustedCertEntry, 
      Certificate fingerprint (SHA-256): 1B:A5:B2:AA:8C:65:40:1A:82:96:01:18:F8:0B:EC:4F:62:30:4D:83:CE:C4:71:3A:19:C3:9C:01:1E:A4:6D:B4
      amazonrootca3 [jdk], May 26, 2015, trustedCertEntry, 
      Certificate fingerprint (SHA-256): 18:CE:6C:FE:7B:F1:4E:60:B2:E3:47:B8:DF:E8:68:CB:31:D0:2E:BB:3A:DA:27:15:69:F5:03:43:B4:6D:B3:A4
      amazonrootca4 [jdk], May 26, 2015, trustedCertEntry, 
      Certificate fingerprint (SHA-256): E3:5D:28:41:9E:D0:20:25:CF:A6:90:38:CD:62:39:62:45:8D:A5:C6:95:FB:DE:A3:C2:2B:0B:FB:25:89:70:92
      ...
      ```
      Since you have certificate issues, I'd expect that you won't see the output above. Please confirm whether it's correct. If that's the case, you will have to add the amazon root certificates manually. Let me know if you have any issues doing so.

**Comment by vikashprajapati** [comment]
After trying above steps I m getting same logs just like yours. What I tried further was I downloaded the certificate associated with https://maven.fpregistry.io/releases/com/fingerprint/android/pro/2.3.1/pro-2.3.1.pom and added it in my JVM cacerts, this resolved the issue.
